[sprite]
    image='img/guns/revolver.png'
    zOrder=3
    scale=[32,16]

[weapon]
    fireRate = 0.2
    magazineSize = 6
    reloadTime = 1
    spread = 15
    bulletType = 'playerBullet'
    muzzlePosition=[10,0]
