persistent=true

[sprite]
    image='img/guns/revolver.png'
    zOrder=3
    scale=[32,16]

[weapon]
    fireRate = 0.2
    magazineSize = 6
    reloadTime = 0.5
    spread = 15
    bulletType = 'playerBullet'
    meleeType = 'playerMeleeSwipe' 
    muzzlePosition=[16,0]
    meleeOffset=[0,0]
    weaponOffset=[20, 0, 10]
    useParentForAim=true
    rotateToAimVector=true

[flickMelee]
  damage=5
  cooldown=1
  flickTriggerDelta=3
  deltaAccumulationTime=0.25