[gamepadSettings]
    deadZone=0.1

# forward-axis movement
[[actions.forward]]
    key="w"
    amount=1

[[actions.forward]]
    key="s"
    amount=-1

[[actions.forward]]
    gamepad="axis1"
    amount=-1

# right-axis movement
[[actions.right]]
    key="d"
    amount=1

[[actions.right]]
    key="a"
    amount=-1

[[actions.right]]
    gamepad="axis0"
    amount=1

# up-axis movement
[[actions.up]]
    key="x"
    amount=1

[[actions.up]]
    key="c"
    amount=-1

# forward-axis look
[[actions.lookforward]]
    key="up"
    amount=1

[[actions.lookforward]]
    key="down"
    amount=-1

[[actions.lookforward]]
    gamepad="axis3"
    amount=-1

# right-axis movement
[[actions.lookright]]
    key="right"
    amount=1

[[actions.lookright]]
    key="left"
    amount=-1

[[actions.lookright]]
    gamepad="axis2"
    amount=1

# attack action
[[actions.fire]]
    key="space"
    amount=1

[[actions.fire]]
    gamepad=5
    amount=1