[gamepadSettings]
    deadZone=0.1

# forward-axis movement
[[actions.forward]]
    key="w"
    amount=1

[[actions.forward]]
    key="s"
    amount=-1

[[actions.forward]]
    gamepad="axis1"
    amount=-1

# right-axis movement
[[actions.right]]
    key="d"
    amount=1

[[actions.right]]
    key="a"
    amount=-1

[[actions.right]]
    gamepad="axis0"
    amount=-1

# up-axis movement
[[actions.up]]
    key="x"
    amount=1

[[actions.up]]
    key="c"
    amount=-1

# attack action
[[actions.attack]]
    key=" "
    amount=1