bindDepthToY=true
depthOffset=64

[sprite]
    image='img/gateway.png'
    scale=[64, 64]

[spritelight]
    radius=30
    color=[0.6, 0.6, 1.2]
    offset=[0, -10, 0]
    style=1

[levelGenIact]
    destLevel='testcavelevel'
    enemyPointsToSpend = 80
