bindDepthToY=true
depthOffset=64

[sprite]
    image = 'img/bulletgreen.png'
    scale = [8,8]

[collider]
    blocks = false
    radius = 4

[bullet]
    speed = 6

[spritelight]
    radius=4
    color=[0.1, 0.5, 0.1]
