
[sprite]
    image='img/ship.png'

[controller]
    moveSpeed=160

[collider]
    blocks=true
    radius=10

[inventory]
    [[inventory.items]]
    label="wep1"
    x=10
    y=5
    isVisible=true

[interactor]
    radius = 100
