persistent=true

[sprite]
    image='img/characters/wanderer/worldview.png'

[controller]
    moveSpeed=100
    dodgeDistance=100
    dodgeTime=0.4

[collider]
    blocks=true
    radius=3

[inventory]
    [[inventory.items]]
    label="wep1"
    x=10
    y=5
    isVisible=true

[interactor]
    radius = 100

[spritelight]
    radius=50
    color=[1.1, 0.9, 0.9]

[stats]
    health=1

[loadLevelOnDeath]
    levelToLoad="theRoom"
