team = 1
persistent=true
bindDepthToY=true
depthOffset=64

[sprite]
    image='img/characters/wanderer/worldview.png'

[controller]
    moveSpeed=100
    dodgeDistance=100
    dodgeTime=0.4

[collider]
    blocks=true
    radius=3
    collisionMask=1

[inventory]
    [[inventory.items]]
    label="wep1"
    x=10
    y=5
    isVisible=true

[interactor]
    radius = 100

[spritelight]
    radius=50
    color=[1.1, 0.9, 0.9]
    style=0

[stats]
    health=1
    destroyOnDeath=false

[loadLevelOnDeath]
    levelToLoad="theRoom"
