
[sprite]
    image='img/characters/playable1/worldview.png'

[controller]
    moveSpeed=160
    dodgeDistance=100
    dodgeTime=0.4

[collider]
    blocks=true
    radius=10

[inventory]
    [[inventory.items]]
    label="wep1"
    x=10
    y=5
    isVisible=true

[interactor]
    radius = 100
