[[entities]]
    tomlFile="startScreenTitle.toml"

    [entities.position]
        x=0
        y=100

[[entities]]
    tomlFile="startScreenBackground.toml"

    [entities.position]
        x=0
        y=0