[sprite]
    image='img/pressSpace.png'
    zOrder=100
    scale=[200, 50]
    
[sway]
    horizMagnitude=5
    horizFrequency=0.01
    vertMagnitude=2
    vertFrequency=1
    horizTimeOffset=0
    vertTimeOffset=2

[buttonTransition]
    button='space'
    targetLevel='theRoom'