[sprite]
    image='img/titleText.png'
    zOrder=100
    scale=[1000, 500]

[sway]
    horizMagnitude=5
    horizFrequency=0.01
    vertMagnitude=5
    vertFrequency=0.5
    horizTimeOffset=0
    vertTimeOffset=0
