[[entities]]
    label="activeCam"
    tomlFile="camera.toml"

    [entities.position]
        x=0
        y=0

[[entities]]
    tomlFile="startScreenTitle.toml"

    [entities.position]
        x=0
        y=100

[[entities]]
    tomlFile="startScreenBackground.toml"

    [entities.position]
        x=0
        y=0

[[entities]]
    tomlFile="startScreenPrompt.toml"

    [entities.position]
        x=5
        y=-240
