terrainCreationMethod="GenerateCave"
usePixelShader=true

[terrainParams]
    width=50
    height=50
    chanceToFill=0.5
    iterationCount=3
    extentToScan=1
    requiredToFill=6
    requiredToOpen=4
    tileSet="hub"

[[entities]]
    label="hud"
    
    [entities.position]
        x=0
        y=0

[[entities]]
    label="activeCam"
    tomlFile="followingCamera.toml"

    [entities.position]
        x=0
        y=0

[[entities]]
    label="itemTest"
    tomlFile="items/mirrorOfTheDreamingEye.toml"

    [entities.position]
        x=200
        y=200