terrainCreationMethod="GeneratePerfectMaze"
[terrainParams]
    width=10
    height=10

[[entities]]
    label="wep1"
    tomlFile="weapon.toml"

    [entities.position]
        x=0
        y=0

[[entities]]
    tomlFile="player.toml"

    [entities.position]
        x=-100
        y=100

[[entities]]
    tomlFile="testenemy.toml"

    [entities.position]
        x=100
        y=100