terrainCreationMethod="GenerateBoxLevel"
terrainTileSet="hub"

[terrainParams]
    width=10
    height=10
    terrainScale=2

[[entities]]
    tomlFile="world/gateway.toml"
    [entities.position]
        x=300
        y=400

[[entities]]
    label="wep1"
    tomlFile="weapons/revolver.toml"

    [entities.position]
        x=0
        y=0

[[entities]]
    label="player"
    tomlFile="player.toml"

    [entities.position]
        x=150
        y=150

[[entities]]
    tomlFile="testenemy.toml"

    [entities.position]
        x=400
        y=200

[[entities]]
    label="activeCam"
    tomlFile="followingCamera.toml"

    [entities.position]
        x=0
        y=0
