terrainCreationMethod="GenerateBoxLevel"
usePixelShader=true

[terrainParams]
    width=20
    height=15
    tileSet="masonInterior"

[[entities]]
    tomlFile="world/gateway.toml"
    [entities.position]
        x=300
        y=400

[[entities]]
    label="activeCam"
    tomlFile="followingCamera.toml"

    [entities.position]
        x=0
        y=0
