terrainCreationMethod="GenerateBoxLevel"

[terrainParams]
    width=20
    height=15
    tileSet="hub"

[[entities]]
    tomlFile="world/gateway.toml"
    [entities.position]
        x=300
        y=400

[[entities]]
    label="wep1"
    tomlFile="guns/revolver.toml"

    [entities.position]
        x=0
        y=0

[[entities]]
    label="player"
    tomlFile="player.toml"

    [entities.position]
        x=150
        y=150

[[entities]]
    label="activeCam"
    tomlFile="followingCamera.toml"

    [entities.position]
        x=0
        y=0
