terrainCreationMethod="GenerateBoxLevel"
usePixelShader=true

[terrainParams]
    width=20
    height=15
    tileSet="masonInterior"

[[entities]]
    label="hud"
    
    [entities.position]
        x=0
        y=0

[[entities]]
    tomlFile="world/playerEntry.toml"
    [entities.position]
        x=300
        y=100

[[entities]]
    tomlFile="world/gateway.toml"
    [entities.position]
        x=300
        y=400

[[entities]]
    label="activeCam"
    tomlFile="followingCamera.toml"

    [entities.position]
        x=0
        y=0

[[entities]]
    label=""
    tomlFile="chest.toml"

    [entities.position]
        x=200
        y=200

[[entities]]
    label=""
    tomlFile="chest.toml"

    [entities.position]
        x=240
        y=240

[[entities]]
    label=""
    tomlFile="chest.toml"

    [entities.position]
        x=280
        y=280

[[entities]]
    label=""
    tomlFile="chest.toml"

    [entities.position]
        x=240
        y=280
