[sprite]
    image='img/revolver.png'
    zOrder=3
    scale=[32,16]

[weapon]
    fireRate = 0.5
    magazineSize = 6
    reloadTime = 3
    spread = 15
    bulletType = 'playerBullet'
    muzzlePosition=[10,0]
