bindDepthToY=true
depthOffset=64

[stats]
    health=5
    destroyOnDeath=true

[sprite]
    image='img/characters/stalker/stalker.png'

[depthControl]
    zOrder=59

[collider]
    blocks=true
    radius=15

[weapon]
    fireRate = 0.3
    magazineSize = 6
    reloadTime = 3
    spread = 15
    bulletType = 'enemyBullet'
    muzzlePosition=[0,-14]
    weaponOffset=[0,0]
    meleeOffset=[0,0]
    useParentForAim=false
    rotateToAimVector=false

[targetAcquisition]
    detectionRadius = 300
    targetPlayers = true

[deathSpawn]
    spawnSpreadRadius = 10
    [deathSpawn.objects.soul]
        file='soul.toml'
        chance=1