bindDepthToY=true
depthOffset=64

[stats]
    health=5
    destroyOnDeath=true

[sprite]
    image='img/characters/stalker/stalker.png'

[depthControl]
    zOrder=59

[collider]
    blocks=true
    radius=15
    collisionMask=2

[weapon]
    fireRate = 0.8
    magazineSize = 6
    reloadTime = 3
    spread = 15
    bulletType = 'enemyBullet'
    muzzlePosition=[0,-14]
    weaponOffset=[0,0]
    meleeOffset=[0,0]
    useParentForAim=false
    rotateToAimVector=false

[evolutionaryData]
    id='peeperData'
    [evolutionaryData.shotgun]
        prediction='none'
        fireRate=0.01
        magazineSize=10
        reloadTime=10
        spread=90

    [evolutionaryData.veteran]
        prediction='leadTarget'
        fireRate=0.01
        magazineSize=10
        reloadTime=10
        spread=90

    [evolutionaryData.basic]
        prediction='none'
        fireRate=0.01
        magazineSize=10
        reloadTime=10
        spread=90

    [evolutionaryData.chainGunner]
        prediction='none'
        fireRate=0.01
        magazineSize=10
        reloadTime=10
        spread=90

[targetAcquisition]
    detectionRadius = 300
    targetPlayers = true

[deathSpawn]
    spawnSpreadRadius = 10
    [deathSpawn.objects.soul]
        file='soul.toml'
        chance=1